;;; savehist.scm --- Save minibuffer history
;; Author: Laluxx
;; Maintainer: Laluxx
;; Keywords: convenience, minibuffer

;;; Commentary:
;; Many editors (e.g. Vim) have the feature of saving minibuffer
;; history to an external file after exit.  This package provides the
;; same feature in Glemax.  When set up, it saves recorded minibuffer
;; histories to a file (`~/.emacs.d/history' by default).  Additional
;; variables may be specified by customizing
;; `savehist-additional-variables'.

;; To use savehist, turn on savehist-mode by putting in init.scm:
;;
;;     (savehist-mode 1)
;;
;;     ;; Optionally customize variables
;;     (setq savehist-file "~/.config/glemax/history")
;;     (setq savehist-autosave-interval 300) ; 5 minutes
;;
;;     ;; Add custom variables to save
;;     (savehist-add-variable 'my-custom-history)

;;; Code:

(use-modules (ice-9 format)
             (ice-9 pretty-print))

;;; Load timer module if available
(catch #t
  (lambda () (load "timer.scm"))
  (lambda (key . args) #f))

;;; Customizable variables

(define savehist-file
  (string-append user-glemax-directory "history"))
(set-var-doc! 'savehist-file
  "File name where minibuffer history is saved to and loaded from.
The minibuffer history is a series of Scheme expressions that will be loaded
automatically when `savehist-mode' is turned on.")

(define savehist-additional-variables '())
(set-var-doc! 'savehist-additional-variables
  "List of additional variables to save.
Each element is a symbol whose value will be persisted across Glemax sessions.
The variable must be bound and must have a printable Scheme value.")

(define savehist-autosave-interval 300)
(set-var-doc! 'savehist-autosave-interval
  "The interval between autosaves of minibuffer history, in seconds.
If set to #f, disables timer-based autosaving of the minibuffer history.")

(define savehist-save-minibuffer #t)
(set-var-doc! 'savehist-save-minibuffer
  "If non-#f, save minibuffer history (overrides `savehist-save-hook').")

;;; Internal variables

(define savehist-mode #f)
(set-var-doc! 'savehist-mode
  "Mode variable for `savehist-mode'.")

(define savehist--last-autosave-time 0)
(set-var-doc! 'savehist--last-autosave-time
  "Time of last autosave.")

(define savehist--timer #f)
(set-var-doc! 'savehist--timer
  "Timer for autosaving minibuffer history.")

(define savehist-minibuffer-history-variables
  '(minibuffer-history
    extended-command-history
    read-expression-history
    file-name-history))
(set-var-doc! 'savehist-minibuffer-history-variables
  "List of minibuffer history variables to save.")

;;; Core functions

(define (savehist-save)
  "Save minibuffer history to `savehist-file'.
This includes all variables in `savehist-minibuffer-history-variables'
and `savehist-additional-variables'."
  ;; Ensure directory exists
  (let ((dir (dirname savehist-file)))
    (unless (file-exists? dir)
      (mkdir dir)))

  (with-output-to-file savehist-file
    (lambda ()
      (display ";; -*- mode: scheme -*-\n")
      (display ";; Minibuffer history file, automatically generated by savehist.\n")
      (display ";; DO NOT EDIT THIS FILE BY HAND\n\n")

      ;; Save each history variable
      (for-each
       (lambda (var-sym)
         (catch #t
           (lambda ()
             (let ((var (module-variable (current-module) var-sym)))
               (when (and var (variable-bound? var))
                 (let ((value (variable-ref var)))
                   (when (and (list? value) (not (null? value)))
                     (display (format #f ";; History: ~a\n" var-sym))
                     (display "(define ")
                     (display var-sym)
                     (newline)
                     (display "  '")
                     (pretty-print value)
                     (display ")\n\n"))))))
           (lambda (key . args)
             ;; Silently skip variables that can't be saved
             #f)))
       savehist-minibuffer-history-variables)

      ;; Save additional variables
      (for-each
       (lambda (var-sym)
         (catch #t
           (lambda ()
             (let ((var (module-variable (current-module) var-sym)))
               (when (and var (variable-bound? var))
                 (let ((value (variable-ref var)))
                   (display (format #f ";; Additional variable: ~a\n" var-sym))
                   (display "(define ")
                   (display var-sym)
                   (display " ")
                   (write value)
                   (display ")\n\n")))))
           (lambda (key . args)
             ;; Silently skip variables that can't be saved
             #f)))
       savehist-additional-variables)))

  (setq savehist--last-autosave-time (current-time))
  (message "Saved minibuffer history to %s" savehist-file))

(define (savehist-load)
  "Load minibuffer history from `savehist-file'.
Does nothing if the file doesn't exist."
  (when (file-exists? savehist-file)
    (catch #t
      (lambda ()
        (load savehist-file)
        (message "Loaded minibuffer history from %s" savehist-file))
      (lambda (key . args)
        (message "Error loading savehist file: %s" key)))))

(define (savehist-autosave)
  "Save minibuffer history if enough time has passed since last save.
This is called periodically when `savehist-mode' is active."
  ;; This function is now only needed if not using the timer system
  ;; It's kept for backwards compatibility
  (when (and savehist-mode
             savehist-autosave-interval
             (number? savehist-autosave-interval))
    (let ((now (current-time)))
      (when (>= (- now savehist--last-autosave-time)
                savehist-autosave-interval)
        (savehist-save)))))

(define (savehist-unload-function)
  "Called when savehist mode is being disabled or Glemax is exiting.
Saves the history one last time before unloading."
  (when savehist-mode
    (savehist-save)))

;;; Mode definition (Global minor mode)

(define (savehist-mode . args)
  "Toggle saving of minibuffer history (Savehist mode).
This is a global minor mode.  When Savehist mode is enabled, minibuffer
history is saved to `savehist-file' periodically and when exiting Glemax.

The history is loaded automatically when this mode is enabled.

With prefix argument ARG, enable Savehist mode if ARG is positive,
and disable it otherwise.  If called from Scheme, enable the mode
if ARG is omitted or nil."
  (let ((arg (if (null? args) 'toggle (car args))))
    (let ((new-value (cond
                      ((eq? arg 'toggle) (not savehist-mode))
                      ((number? arg) (> arg 0))
                      (else arg))))

      (unless (eq? savehist-mode new-value)
        (setq savehist-mode new-value)

        (if savehist-mode
            (savehist-mode-enable)
            (savehist-mode-disable))

        ;; Return the new value
        savehist-mode))))

(define (savehist-mode-enable)
  "Enable savehist mode."
  ;; Load existing history first
  (savehist-load)

  ;; Add hook to save on exit
  (add-hook 'kill-glemax-hook savehist-unload-function)

  ;; Set up autosave timer if interval is set and timer system is available
  (when (and savehist-autosave-interval
             (number? savehist-autosave-interval)
             (defined? 'run-at-time))
    (setq savehist--timer
          (run-at-time savehist-autosave-interval
                       savehist-autosave-interval
                       savehist-save)))

  (message "Savehist mode enabled"))

(define (savehist-mode-disable)
  "Disable savehist mode."
  ;; Save one last time before disabling
  (savehist-save)

  ;; Remove hook
  (remove-hook 'kill-glemax-hook savehist-unload-function)

  ;; Cancel timer if it exists
  (when (and savehist--timer (defined? 'cancel-timer))
    (cancel-timer savehist--timer)
    (setq savehist--timer #f))

  (message "Savehist mode disabled"))

;;; Helper functions for integration

(define (savehist-add-variable var-sym)
  "Add VAR-SYM to the list of variables saved by savehist.
This makes it easy to add custom variables to be persisted."
  (unless (memq var-sym savehist-additional-variables)
    (setq savehist-additional-variables
          (cons var-sym savehist-additional-variables))
    (when savehist-mode
      (savehist-save))))

(define (savehist-remove-variable var-sym)
  "Remove VAR-SYM from the list of variables saved by savehist."
  (setq savehist-additional-variables
        (delq var-sym savehist-additional-variables)))

;;; Interactive commands

(define (savehist-save-immediately)
  "Save history immediately, regardless of autosave interval."
  (savehist-save))
